apiVersion: v1
kind: Service
metadata:  
  name: my-nodeport-service
spec:
  selector:    
    app: tpg-sctp-app 
  type: NodePort
  ports:  
  - name: tpgsctp
    port: 15000
    targetPort: 15000
    nodePort: 30036
    protocol: TCP
